fix file：ezdown

diff --git a/ezdown b/ezdown
--- a/ezdown
+++ b/ezdown
@@ -127,7 +127,7 @@ EOF
     "https://hub.rat.dev",
     "https://docker.amingg.com"
   ],
-  "insecure-registries": ["http://duoli.io.local:5000"],
+  "insecure-registries": ["http://kubemid.io.local:5000"],
   "max-concurrent-downloads": 10,
   "log-driver": "json-file",
   "log-level": "warn",
@@ -143,7 +143,7 @@ EOF
     cat > /etc/docker/daemon.json << EOF
 {
   "exec-opts": ["native.cgroupdriver=$CGROUP_DRIVER"],
-  "insecure-registries": ["http://duoli.io.local:5000"],
+  "insecure-registries": ["http://kubemid.io.local:5000"],
   "max-concurrent-downloads": 10,
   "log-driver": "json-file",
   "log-level": "warn",
@@ -169,12 +169,12 @@ EOF
 
 function get_kubemid() {
   # check if kubemid already existed
-  [[ -d "$BASE/roles/kube-node" ]] && { logger warn "kubeasz already existed"; return 0; }
+  [[ -d "$BASE/roles/docker" ]] && { logger warn "kubemid already existed"; return 0; }
 
   if [[ ! -f "$imageDir/kubemid_$KUBEMID_VER.tar" ]];then
     logger info "downloading kubemid: $KUBEMID_VER"
-    docker pull "easzlab/kubeasz:$KUBEMID_VER" && \
-    docker save -o "$imageDir/kubemid_$KUBEMID_VER.tar" "easzlab/kubeasz:$KUBEMID_VER" || \
+    docker pull "kubemid/kubemid:$KUBEMID_VER" && \
+    docker save -o "$imageDir/kubemid_$KUBEMID_VER.tar" "kubemid/kubemid:$KUBEMID_VER" || \
     { logger error "download failed!"; return 1; }
   else
     docker load -i "$imageDir/kubemid_$KUBEMID_VER.tar"
@@ -182,7 +182,7 @@ function get_kubemid() {
 
   docker ps -a |grep -q temp_easz && { logger debug "remove existing container"; docker rm -f temp_easz; }
   logger debug " run a temporary container"
-  docker run -d --name temp_easz easzlab/kubeasz:${KUBEMID_VER} || { logger error "failed."; exit 1; }
+  docker run -d --name temp_easz kubemid/kubemid:${KUBEMID_VER} || { logger error "failed."; exit 1; }
 
   [[ -d "$BASE/down" ]] && /bin/mv -f "$BASE/down" /tmp
   [[ -d "$BASE/bin" ]] && /bin/mv -f "$BASE/bin" /tmp
@@ -227,14 +227,14 @@ function start_kubemid_docker() {
   sed -i '/docker exec/d' /root/.bashrc
   echo "alias dk='docker exec -it kubemid'  # generated by kubemid" >> /root/.bashrc
 
-  [[ -d "$BASE/roles/kube-node" ]] || { logger error "not initialized. try 'ezdown -D' first."; exit 1; }
+  [[ -d "$BASE/roles/docker" ]] || { logger error "not initialized. try 'ezdown -D' first."; exit 1; }
   docker ps -a --format="{{ .Names }}"|grep kubemid > /dev/null 2>&1 && \
   docker rm -f kubemid > /dev/null
 
   if [[ ! -f "$imageDir/kubemid_$KUBEMID_VER.tar" ]];then
     logger info "downloading kubemid: $KUBEMID_VER"
-    docker pull "easzlab/kubemid:$KUBEMID_VER" && \
-    docker save -o "$imageDir/kubemid_$KUBEMID_VER.tar" "easzlab/kubemid:$KUBEMID_VER"
+    docker pull "kubemid/kubemid:$KUBEMID_VER" && \
+    docker save -o "$imageDir/kubemid_$KUBEMID_VER.tar" "kubemid/kubemid:$KUBEMID_VER"
   else
     docker load -i "$imageDir/kubemid_$KUBEMID_VER.tar"
   fi
@@ -260,10 +260,10 @@ function start_kubemid_docker() {
       --network host \
       --restart always \
       --volume "$BASE":"$BASE" \
-      --volume /root/.kube:/root/.kube \
+      # --volume /root/.kube:/root/.kube \
       --volume /root/.ssh:/root/.ssh \
       --volume /etc/docker:/etc/docker \
-      easzlab/kubemid:${KUBEMID_VER}
+      kubemid/kubemid:${KUBEMID_VER}
 }
 
 function clean_container() {
@@ -297,7 +297,7 @@ function download_all() {
   download_docker && \
   install_docker && \
   get_kubemid && \
-  start_local_registry
+  # start_local_registry
 }
 
 function main() {
@@ -329,6 +329,9 @@ function main() {
           { usage-down-sys-pkg; exit 1; }
           SYS_PKG_VER="${SYS_PKG_VER}_$OPTARG"
           ACTION="get_sys_pkg $OPTARG"
+          ;;
+        S)
+          ACTION="start_kubemid_docker"
           ;;
         X)
           ACTION="get_extra_images $OPTARG"
